### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by KFoxder** [highcharts/highcharts-jsdom#10]
@TorsteinHonsi Do you mind merging in the dependabot updates?

**Comment by TorsteinHonsi** [comment]
Sure, thanks for following up! I merged most of them, but jsdom is so essential I'd like to test properly first.

**Comment by TorsteinHonsi** [comment]
@KFoxder I now updated jsdom to v20. Published to GitHub and npm. Thanks for your patience!
